### ISSUE TITLE
Changing the Behavior of the Selector

### ISSUE THREAD

**Issue by sethazazel** [CogentRedTester/mpv-file-browser#17]
I think it would be better if the selector pointed to the video that is currently playing.

Simple examples: [https://imgur.com/a/nbwmNCN](https://imgur.com/a/nbwmNCN)

(sorry for my bad English)

**Comment by CogentRedTester** [comment]
Yea, probably a good idea. What do you think the preference should be when moving up a directory? Should it still highlight the directory that you just moved out of, or should it focus on the playing file?

I'm thinking prefer the folder when moving up a directory, otherwise prefer the playing entry?

**Comment by sethazazel** [comment]
i think highlighting the directory that you just moved out of is a better choice.

**Comment by CogentRedTester** [comment]
Should be working now, let me know if you notice any weird behaviour.

**Comment by sethazazel** [comment]
There is one weird behavior.

1- Open a video
2- Change directory
3- Play a folder that have multiple subfolders (with ENTER)(Not file Whole Folder)
4- Now selector highlights currently playing file's folder

**Comment by CogentRedTester** [comment]
That is deliberate behaviour, I decided it might be useful to have a highlighted path to the playing file.

**Comment by sethazazel** [comment]
First i thought it was a bug but after playing with it a few times i noticed that it is a good behaviour. Thank you for quickly responding and adding my request.
