### ISSUE TITLE
How to run this application

### ISSUE THREAD

**Issue by rsingh2083** [CogentRedTester/mpv-file-browser#27]
Can anyone please help how to run this app ?
I ran
`lua file-browser.lua`
But got these errors :-
```
└──╼ $lua file-browser.lua 
lua: file-browser.lua:11: module 'mp' not found:
	no field package.preload['mp']
	no file '/usr/local/share/lua/5.2/mp.lua'
	no file '/usr/local/share/lua/5.2/mp/init.lua'
	no file '/usr/local/lib/lua/5.2/mp.lua'
	no file '/usr/local/lib/lua/5.2/mp/init.lua'
	no file '/usr/share/lua/5.2/mp.lua'
	no file '/usr/share/lua/5.2/mp/init.lua'
	no file './mp.lua'
	no file '/usr/local/lib/lua/5.2/mp.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/mp.so'
	no file '/usr/lib/lua/5.2/mp.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './mp.so'
stack traceback:
	[C]: in function 'require'
	file-browser.lua:11: in main chunk
	[C]: in ?
```

**Comment by CogentRedTester** [comment]
This script can only be loaded by mpv player. You need to place the lua file inside the scripts folder inside the mpv config directory. MPV will run the script on startup and you can open the browser from within the player. 

See [here](https://mpv.io/manual/master/#script-location) for more details.

**Comment by rsingh2083** [comment]
Its still not working.
```
$:> pwd
/home/ns/.config/mpv
$:> ls
script-modules  scripts
$:> ls scripts
file-browser.lua  mpv-file-browser  user-input.lua
$:> ls scripts/mpv-file-browser/
addons  custom-keybinds.md  file_browser.conf  file-browser-keybinds.json  file-browser.lua  LICENSE  README.md
```

**Comment by CogentRedTester** [comment]
I believe this script requires at least mpv v0.31, what version are you using?

**Comment by rsingh2083** [comment]
mpv --version
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.8-0ubuntu0.2

**Comment by CogentRedTester** [comment]
Well whatever package manager you're using clearly doesn't have a new enough version of mpv to support this script.

**Comment by CogentRedTester** [comment]
If you get a newer version of mpv the script should work fine. You will want to remove the file-browser folder from the scripts directory, newer versions of mpv treat folders inside that directory differently (see #26).

I won't be backporting the script to an older version since they lack some inbuilt functions that the script relies on, so installing a newer version is your only option.

If you want user-input to work correctly make sure that the `user-input-module.lua` file is in the correct `script-modules` directory as explained in that github page.

If you have any other issues related to setting up the script please use the discussions tab and only open issues for things you believe are bugs or crashes in the script.
