### ISSUE TITLE
Mark files as watched and set favourites

### ISSUE THREAD

**Issue by ereinstein** [CogentRedTester/mpv-file-browser#30]
First of all, this is a great script. I have two feature requests which might bring this script to the next level. 

1. Mark videos which have already been watched and hide them from the media browser. Both automatically when closing the video at e.g. 95%+ of its runtime and manually by hitting a certain key. There should of course be option to toggle visibility of files marked as watched. If all files in a directory are marked as watched, hide the directory as well. This should of course work recursively as well. Example: If your file structure looks like

    - root
        - show X
            - season 1
                - episode 1
                - episode 2 
                - ... 
            - season 2
                - episode 1
                - episode 2
                - ...  

    and you completely watch all episodes in `season 1` and `season 2`, `show X` should be hidden as well, not only `season 1` and `season 2` inside of `show X`.
2. Mark files as favourites and populate them in a virtual directory at the top of the root directory. 

Those two options would vastly enhance the use case of this script from mere file browser to a proper file manager. This might even work as a barebones and lightweight alternative to other media management tools like Jellyfin. Of course, many features which are in such media management tools will be missing but the most important basic functionality of marking things as watched, picking it back up where you left from and marking files favourites will still be present this way.

**Comment by CogentRedTester** [comment]
I can definitely see the usecase for these features, but I won't be implementing them into the main script because I'm trying to keep it from getting too bloated. However, these are features which could likely be implemented using the addon system, and in fact I already made an example [favourites](https://github.com/CogentRedTester/mpv-file-browser/blob/master/addons/favourites.lua)
script that works very similarly to how you're describing.

However, I think you are vastly underestimating how long it would take to recursively check every folder for watched files. If you're in a high level directory like the user's home directory there would be tens of thousands of folders to check, it would make navigating take a very long time.

**Comment by ereinstein** [comment]
> data file to be a .txt file

This was the issue. It wasn't clear to me that it was supposed to be a .txt file. The error message was talking about directories as well so I just assumed it has to be one. Thanks for your help!

**Comment by CogentRedTester** [comment]
If any of the features in the issue are ever picked up as an addon I will ping this thread. However, as there are no plans to do so, I will be closing this issue.
