### ISSUE TITLE
Alias for root directories, prohibit going higher in the directory structure in root directories

### ISSUE THREAD

**Issue by ereinstein** [CogentRedTester/mpv-file-browser#36]
![Directory structure example](https://user-images.githubusercontent.com/88436802/145509526-5dfee515-6c91-4146-b63f-e4f606ec6ce7.png)

This is what my root directory structure looks like. I find it kind of ugly that I can see the whole path I typed into my configuration file. I think this overview could be a lot neater if one could choose aliases for the root directories. You would then see e.g. 
```
Favourites
New Shit
Anime
```
instead of the paths. 

Likewise, it'd be quite useful if the file-browser could be limited to directories which are lower in the hierarchy than your root directory you are currently browsing. When I start out in e.g. `~/Videos/New Shit`, I'd never want to go up from there to e.g. `~/Videos` which does happen if you open the root directory `~/Videos/New Shit` and try going back by using `Left`.. Sure, `Shift + HOME` does exist but what's the point of being able to go up from the root directory you chose. If I wanted to access directories higher up, I'd have placed my root directory higher up. Pressing `Left` a few times is also a lot faster than moving your hands to `Shift + HOME`.

**Comment by CogentRedTester** [comment]
This can be done already with a custom [addon] (https://github.com/CogentRedTester/mpv-file-browser/blob/master/addons/addons.md). I haven't documented it yet, but if you can leave out `parse` and `can_parse` and you'll be able to create a non - parser addon. Inside the setup function you can use the [create_root_item](https://github.com/CogentRedTester/mpv-file-browser/blob/master/addons/addons.md#api-functions) funding to create custom root items. For the forehand of those items, see [here](https://github.com/CogentRedTester/mpv-file-browser/blob/master/addons/addons.md#the-list-array) for how an item is formatted.

**Comment by CogentRedTester** [comment]
I may make an official addon which does this at some point, or you could.

**Comment by CogentRedTester** [comment]
As for not going higher than the root items, that is not currently possible without an extensive addon such as Favourites. However, I definitely see the use, and I think I see a way to implement it that is not too difficult. However, any jumping, such as to the current directory, would break it, since the browser has no way of knowing if you are jumping around within the same root item.

**Comment by CogentRedTester** [comment]
Note that this is not what the root is designed for, moving to commonly used directories is what Favourites is for.

**Comment by ereinstein** [comment]
Then I must have misunderstood root. My impression was that you use root for directories which contain the content you want to access and your favourites are for keeping track of particular pieces of content (e.g. episodes, seasons or whole shows). Putting my commonly used directories into Favourites works as I want it to but I need to take one more step before accessing my commonly used directories. 

I'd understand it if you didn't want to bother too much though since Favourites does the trick and I am being a bit nitpicky.

**Comment by CogentRedTester** [comment]
You could always bind a button to open the favourites menu and use that when first opening the browser.

**Comment by CogentRedTester** [comment]
> Then I must have misunderstood root. My impression was that you use root for directories which contain the content you want to access and your favourites are for keeping track of particular pieces of content (e.g. episodes, seasons or whole shows). Putting my commonly used directories into Favourites works as I want it to but I need to take one more step before accessing my commonly used directories.
> 
> I'd understand it if you didn't want to bother too much though since Favourites does the trick and I am being a bit nitpicky.

Let me just respond to this, since I forgot last week.

It is important to note that file-browser is designed to be a browser, not a media manager. File-browser allows you to navigate a file-system to open files. Think of it like the open file dialogue box that pops up when you want to upload something to the internet. In this analogy the root directory is supposed to be like `This PC` on windows, a place to see all the top level file systems, it's not for random favourite folders.

In this sense, the fact that the default root entry is the home folder `~/` may be misleading. However, the reason I have that as the default is simple, because it is the only useful path that works on both Windows and Linux. Additionally, for people who don't install any addons, it is usually desirable to be able to skip straight to the home directory.

**Comment by CogentRedTester** [comment]
Note that this has been possible for a while with the [root addon](https://github.com/CogentRedTester/mpv-file-browser/blob/master/addons/root.lua). In addition, the latest commit has made navigating back to the root much easier as unless you perform a goto/seek operation (jumping to the current file) the browser will now remember the series of directories you moved through and jump straight back to the root.
