### ISSUE TITLE
wrap-around the file-list when reaching the top or the bottom

### ISSUE THREAD

**Issue by garoto** [CogentRedTester/mpv-file-browser#51]
Handy for very large directory listings. Keybinds to go to the top or bottom of the listing can be an equivalent functionality I guess.

**Comment by dyphire** [comment]
https://github.com/CogentRedTester/mpv-file-browser/blob/b6f03cba1e565b95493dadd42d737d7e7a5486c5/file-browser.lua#L690-L712

In fact, the function of wrap scrolling has been implemented in the code, but it has not been enabled.

I think we can put the state.wrap is changed to o.wrap so that the user can decide whether to cycle wrap scrolling.

**Comment by CogentRedTester** [comment]
Hmm yea, I forgot about that. The wrap code must be a holdover from the mpv-scroll-list implementation. What @dyphire suggests will indeed work. I'll try to do it in the next couple of days if I have time.

**Comment by CogentRedTester** [comment]
Should be supported now.

**Comment by garoto** [comment]
Working fine, thanks!
