### ISSUE TITLE
There is a conflict between windir.lua and BD folder playback.

### ISSUE THREAD

**Issue by dyphire** [CogentRedTester/mpv-file-browser#57]
Precondition: add BD and DVD file types to the white list of extensions.
```ini
extension_whitelist=bdmv;ifo;iso
```

When file-browser uses the addon of  windir.lua and directly plays for the BD folder, the BD folder will fail to play. 
When the addon of  windir.lua is not used, the BD folder will be loaded and played normally.

Here are the log files:
[mpv_nor.txt](https://github.com/CogentRedTester/mpv-file-browser/files/8746888/mpv_nor.txt)
[mpv_err.txt](https://github.com/CogentRedTester/mpv-file-browser/files/8746891/mpv_err.txt)

**Comment by dyphire** [comment]
After testing, it also appears in  the addon of powershell.lua.

**Comment by CogentRedTester** [comment]
I'm going to need a better idea of what is going on. What is the entire file structure of the folder you are trying to open? What are the file extension types? What does the playlist look like before/after when using and not using the addons. Some screenshots might be helpful.

Also do a log using `--msg-level=file_browser='trace'`

**Comment by CogentRedTester** [comment]
Is this a Blu-ray rip, or is it a Blu-Ray Disc in a disc drive?

**Comment by CogentRedTester** [comment]
If you could provide a link to some files that exhibit this behaviour that would also be a big help.

**Comment by dyphire** [comment]
> Is this a Blu-ray rip, or is it a Blu-Ray Disc in a disc drive?
If you could provide a link to some files that exhibit this behaviour that would also be a big help.

It is similar to the file structure of Blu ray disc. You can find a large number of similar files in this link: https://nyaa.si/?f=0&c=0_0&q=bdmv

**Comment by dyphire** [comment]
> I'm going to need a better idea of what is going on. What is the entire file structure of the folder you are trying to open? What are the file extension types? What does the playlist look like before/after when using and not using the addons. Some screenshots might be helpful.
> 
> Also do logs using `--msg-level=file_browser='trace'`

Screenshot of playlist loaded as folder and played successfully
![image](https://user-images.githubusercontent.com/61936050/169634591-ab6cf3f3-b1db-4071-ae82-cbc0650a725d.png)

**Comment by CogentRedTester** [comment]
Can you send me those trace logs? I've partially downloaded a BDMV torrent, but it'll be a while before it finishes. So far things seem to be working ok on my side though.

**Comment by CogentRedTester** [comment]
I have just updated `win-dir` with better trace messages, so doing a trace log will be more helpful now

**Comment by dyphire** [comment]
> Can you send me those trace logs? I've partially downloaded a BDMV torrent, but it'll be a while before it finishes. So far things seem to be working ok on my side though.
I have just updated win-dir with better trace messages, so doing a trace log will be more helpful now

This is trace log: 
[tracelog.txt](https://github.com/CogentRedTester/mpv-file-browser/files/8746968/tracelog.txt)

**Comment by dyphire** [comment]
When After the extension of 'bdmv' is disabled, it can be loaded into the folder and played normally, but this does not really solve the issue.
![image](https://user-images.githubusercontent.com/61936050/169636170-6fb80a8c-7b95-4a36-b03d-df1bc9654756.png)

**Comment by CogentRedTester** [comment]
Ok, I have identified the issue. The problem is that `bdmv` is not a format that mpv inherently supports. Some `bdmv` files like the `MovieObject.bdmv` work using mpv's `bluray://` parser, but this doesn't seem to work for everything.

What is happening here is that the first item in the playlist is an incompatible `bdmv` file, and the player is aborting. Now normally mpv would just skip to the next item in the playlist and try that, however `windir.lua` and `powershell.lua` use asynchronous IO calls, which means that there is a delay between the files of different directories being added. Essentially because the files are not all added at once mpv tries to load the `bdmv` files, fails, sees there are no more items in the playlist, and exits before the other items can be added to the playlist. This is not a problem with the default parser because it is not asynchronous.

The solution to this is to set mpv to `--idle=yes` so that it does not exit on an error, and to change how I'm appending items to the playlist to always attempt to play items after the first one. I will be pushing a new commit soon that does these things automatically.

**Comment by CogentRedTester** [comment]
I believe the latest commit will have solved the issue, can you please confirm?

**Comment by dyphire** [comment]
> I believe the latest commit will have solved the issue, can you please confirm?

Yes, after a simple test, it works.
