### ISSUE TITLE
Modifying Default Keybind does not work

### ISSUE THREAD

**Issue by georgjaehnig** [CogentRedTester/mpv-file-browser#65]
Hello,

I want to modify the `open_browser` keybind to `b`.

This is what I tried:

- `~~/script-opts/file_browser.conf`: `custom_keybinds=yes`
- `~~/script-opts/file-browser-keybinds.json`:

      [
          {
              "key": "b",
              "command": ["script-binding", "file_browser/dynamic/open_browser"]
          }
      ]

But nothing happens when pressing `b`.

Interestingly, also a dummy keybind gets no reaction:

      [
          {
              "key": "p",
              "command": ["print-text", "spam-text"],
              "flags": {
                  "repeatable": true
              }
          }
      ]

(Using mpv 0.34.0 on macOS 11.6.)

**Comment by CogentRedTester** [comment]
Custom keybinds are for dynamic keybinds that are activated when the browser is open, it sounds like you're trying to use these keybinds when the browser is closed. If you just want a normal keybind then use `input.conf` like all other mpv keybinds.

Since the `open_browser` and `browse-files` keybinds are not dynamic they also don't have `dynamic` in the name, so you should put something like `b script-binding file_browser/open_browser` into `input.conf`.
