### ISSUE TITLE
Replace `shared-script-properties` with `user-data`

### ISSUE THREAD

**Issue by stax76** [CogentRedTester/mpv-file-browser#98]
There is a new warning message on the terminal, which I find distracting.

The warn message:

The shared-script-properties property is deprecated and will be removed in the future. Use the user-data property instead.

**Comment by AziRizvi** [comment]
> There is a new warning message on the terminal, which I find distracting.
> 
> The warn message:
> 
> The shared-script-properties property is deprecated and will be removed in the future. Use the user-data property instead.

MPV team removed the shared-script-properties but this repo hasn't been updated which I actually find strange because @dyphire is a contributor in this repository.

**Comment by dyphire** [comment]
> MPV team removed the shared-script-properties but this repo hasn't been updated which I actually find strange because @dyphire is a contributor in this repository, I hope they update it soon.

It should be pointed out that mpv has not yet deleted this attribute and only issued a warning of deprecation. mpv is expected to officially remove this attribute after the release of 0.37, and there will be no further warnings of deprecation at that time.

ref https://github.com/mpv-player/mpv/pull/12456. We are actually ready to delete it: #96

**Comment by CogentRedTester** [comment]
Adding to what @dyphire said, even when the property is actually removed, we still won't be removing support for it because file-browser officially supports versions of mpv going back to v0.31, and user-data does not exist for those versions.

This new deprecation message is annoying though. Perhaps we can add a config option to force disable shared-script-properties support.

**Comment by stax76** [comment]
> Perhaps we can add a config option to force disable shared-script-properties support.

That would be a good solution, I think.

**Comment by stax76** [comment]
Thanks! The warning is gone, and my code works, but there still might be an issue.

```Lua
mp.observe_property("user-data/file_browser/open", "string", function (name, value)
    if value == '"yes"' then

    end
end)
```

Value isn't `yes` as 3 character string as expected but `"yes"`, it has 5 characters, there are double quotes before and after yes.

For me, this appears to be a mpv bug. I tried searching the mpv issue tracker for `user-data AND observe_property` but that gives no results.

**Comment by CogentRedTester** [comment]
> Thanks! The warning is gone, and my code works, but there still might be an issue.
> 
> ```lua
> mp.observe_property("user-data/file_browser/open", "string", function (name, value)
>     if value == '"yes"' then
> 
>     end
> end)
> ```
> 
> value isn't `yes` as 3 character string as expected but `"yes"`, it has 5 characters, there are double quotes before and after yes.
> 
> For me, this appears to be a mpv bug. I tried searching the mpv issue tracker for `user-data AND observe_property` but that gives no results.

I believe you need to set the type to native instead of string, the documentation says this:

> Converting this property or its sub-properties to strings will give a JSON representation. If converting a leaf-level object (i.e. not a map or array) and not using raw mode, the underlying content will be given (e.g. strings will be printed directly, rather than quoted and JSON-escaped).

On another note, we should test if user-data can contain booleans, if would be better than using 'yes' 'no' strings.

**Comment by stax76** [comment]
I tried it, booleans work.

**Comment by CogentRedTester** [comment]
Ok, since the deprecation message problem is solved I am going to close this issue.

I will also be changing the `user-data/file_browser/open` field to use booleans instead of strings. This may break some people's profiles, but it makes the property nicer to use in auto profiles (`user_data.file_browser.open` vs `user_data.file_browser.open == 'yes'`) and it better reflects the actual binary nature of the property. I figure this is also the best time to do it since this deprecation message will likely push people over to using `user-data`.
